name: steps examples
on: 
  workflow_dispatch
#jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Steps examples"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14
      - name: node verification
        run: node -v 
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - id: step-caller
        uses: "./.github/actions/hello"
        with:
          the-caller: 'Myself'
      - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
        shell: bash
